install: 
  - pip install pytest pytest-cov codecov python-dateutil requests mock matplotlib
language: python
python:
  - "3.8"
arch:
  - amd64
  - arm64
script:
  - python setup.py install --force
  - pip install tcex[development]
  - pytest
